version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
  redis:
    image: redis:3.0
    ports:
      - "6379:6379"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025"